name: Deploy

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: SCP FOLDER
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  PASSWORD: ${{ secrets.PASSWORD }}
              with:
                  source: "."
                  target: "/var/www/tranining/reactjs-ecommerce"
                  node-version: '14.x'

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  HOST: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  script: |
                      cd /var/www/tranining/reactjs-ecommerce
                      git pull origin master
                      npm install
                      npm run build
#                      pm2 restart api-ecm
