name: Deploy

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: SCP FOLDER
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  PASSWORD: ${{ secrets.PASSWORD }}
              with:
                  source: "."
                  target: "/var/www/tranining/reactjs-ecommerce"

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  HOST: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  node-version: ${{ matrix.node-version}}
                  script: |
                      cd /var/www/tranining/reactjs-ecommerce
                      git pull origin master
                      npm install
                      npm run build
#                      pm2 restart api-ecm
